//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPIMEntities : DbContext
    {
        public BDPIMEntities()
            : base("name=BDPIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EBRX_BANCO_CONTA> EBRX_BANCO_CONTA { get; set; }
        public virtual DbSet<EBRX_CARTEIRA> EBRX_CARTEIRA { get; set; }
        public virtual DbSet<EBRX_CLIENT_SOLICIT> EBRX_CLIENT_SOLICIT { get; set; }
        public virtual DbSet<EBRX_CLIENTE> EBRX_CLIENTE { get; set; }
        public virtual DbSet<EBRX_CONTA> EBRX_CONTA { get; set; }
        public virtual DbSet<EBRX_EXTRATO_CONTA> EBRX_EXTRATO_CONTA { get; set; }
        public virtual DbSet<EBRX_FUNC_PROFILE> EBRX_FUNC_PROFILE { get; set; }
        public virtual DbSet<EBRX_FUNCRH> EBRX_FUNCRH { get; set; }
        public virtual DbSet<EBRX_HIST_COD> EBRX_HIST_COD { get; set; }
        public virtual DbSet<EBRX_ORDER> EBRX_ORDER { get; set; }
        public virtual DbSet<EBRX_TIP_ORDR> EBRX_TIP_ORDR { get; set; }
        public virtual DbSet<EBRX_TIP_TRAN> EBRX_TIP_TRAN { get; set; }
        public virtual DbSet<INSTI_BANCO> INSTI_BANCO { get; set; }
        public virtual DbSet<EBRX_COTACAO> EBRX_COTACAO { get; set; }
        public virtual DbSet<EBRX_MOEDA> EBRX_MOEDA { get; set; }
        public virtual DbSet<EBRX_SOLICT> EBRX_SOLICT { get; set; }
        public virtual DbSet<EBRX_TRAN> EBRX_TRAN { get; set; }
    }
}
