//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_EXTRATO_CONTA
    {
        public int EBRX_CLIENTE_CLI_COD { get; set; }
        public Nullable<int> EBRX_ORDER_COD { get; set; }
        public Nullable<int> EBRX_TRAN_COD { get; set; }
        public Nullable<double> VLR_DOU_TRAN { get; set; }
        public string QTD_STR_CRIPT { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZC { get; set; }
    
        public virtual EBRX_CLIENTE EBRX_CLIENTE { get; set; }
        public virtual EBRX_ORDER EBRX_ORDER { get; set; }
        public virtual EBRX_TRAN EBRX_TRAN { get; set; }
    }
}
