//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_HIST_COD
    {
        public int COD_INT_ID { get; set; }
        public Nullable<int> EBRX_CLIENTE_CLI_COD { get; set; }
        public string ALTER_DESC { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZAC { get; set; }
    
        public virtual EBRX_CLIENTE EBRX_CLIENTE { get; set; }
    }
}
