//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBRX_ORDER()
        {
            this.EBRX_EXTRATO_CONTA = new HashSet<EBRX_EXTRATO_CONTA>();
        }
    
        public int COD_ORDER { get; set; }
        public Nullable<int> EBRX_TIP_ORDR_COD { get; set; }
        public Nullable<int> EBRX_MOEDA_MOE_COD { get; set; }
        public Nullable<int> EBRX_CLIENTE_CLI_COD { get; set; }
        public Nullable<double> VLR_ORDER { get; set; }
        public string QTD_CRIPT { get; set; }
    
        public virtual EBRX_CLIENTE EBRX_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_EXTRATO_CONTA> EBRX_EXTRATO_CONTA { get; set; }
        public virtual EBRX_MOEDA EBRX_MOEDA { get; set; }
        public virtual EBRX_TIP_ORDR EBRX_TIP_ORDR { get; set; }
    }
}
