//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_CARTEIRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBRX_CARTEIRA()
        {
            this.EBRX_CONTA = new HashSet<EBRX_CONTA>();
        }
    
        public int CAR_INT_ID { get; set; }
        public Nullable<int> EBRX_CLIENT_ID { get; set; }
        public Nullable<int> EBRX_MOEDA_MOE_STR_ID { get; set; }
        public Nullable<double> SALD_STR_CRIP { get; set; }
        public Nullable<double> SALD_STR_DINHR { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZACAO { get; set; }
    
        public virtual EBRX_CLIENTE EBRX_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_CONTA> EBRX_CONTA { get; set; }
        public virtual EBRX_MOEDA EBRX_MOEDA { get; set; }
    }
}
