//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_CLIENT_SOLICIT
    {
        public int PROTOCOL_INT_ID { get; set; }
        public Nullable<int> EBRX_FUNC_PROFILE_COD { get; set; }
        public string EBRX_CLIENTE_CPF { get; set; }
        public Nullable<int> TIP_STR_SOL { get; set; }
        public string DESC_STR_SOL { get; set; }
        public Nullable<int> SITUAC_ATENDMNT { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZCAO { get; set; }
    
        public virtual EBRX_FUNC_PROFILE EBRX_FUNC_PROFILE { get; set; }
        public virtual EBRX_SOLICT EBRX_SOLICT { get; set; }
    }
}
