//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_COTACAO
    {
        public int EBRX_MOEDA_COD { get; set; }
        public Nullable<double> VLR_DOU_COT { get; set; }
    
        public virtual EBRX_MOEDA EBRX_MOEDA { get; set; }
    }
}
