//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_CONTA
    {
        public int ACC_INT_ID { get; set; }
        public Nullable<int> EBRX_CARTEIRA_ID { get; set; }
        public Nullable<int> EBRX_CLIENT_ID { get; set; }
        public string AGC_STR_ACC { get; set; }
        public string CONT_NUM_ACC { get; set; }
        public string DIG_STR_ACC { get; set; }
        public string SENH_STR_ACC { get; set; }
    
        public virtual EBRX_CARTEIRA EBRX_CARTEIRA { get; set; }
        public virtual EBRX_CLIENTE EBRX_CLIENTE { get; set; }
    }
}
