//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBRX_CLIENTE()
        {
            this.EBRX_CARTEIRA = new HashSet<EBRX_CARTEIRA>();
            this.EBRX_CONTA = new HashSet<EBRX_CONTA>();
            this.EBRX_TRAN = new HashSet<EBRX_TRAN>();
            this.EBRX_HIST_COD = new HashSet<EBRX_HIST_COD>();
            this.EBRX_ORDER = new HashSet<EBRX_ORDER>();
        }
    
        public int CLI_INT_ID { get; set; }
        public string NOME_STR_CLI { get; set; }
        public string CPF_STR_CLI { get; set; }
        public Nullable<System.DateTime> DT_NASC_CLI { get; set; }
        public string EMAIL_STR_CLI { get; set; }
        public Nullable<System.DateTime> DAT_INCLS_CLI { get; set; }
        public string STATS_STR_CLI { get; set; }
        public Nullable<System.DateTime> DAT_ATUALIZC { get; set; }
        public string SENH_ACC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_CARTEIRA> EBRX_CARTEIRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_CONTA> EBRX_CONTA { get; set; }
        public virtual EBRX_EXTRATO_CONTA EBRX_EXTRATO_CONTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_TRAN> EBRX_TRAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_HIST_COD> EBRX_HIST_COD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_ORDER> EBRX_ORDER { get; set; }
    }
}
