//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_BANCO_CONTA
    {
        public int COD_INT_CONTA_ID { get; set; }
        public string EBRX_CLIENT_CPF { get; set; }
        public Nullable<int> INSTI_BANCO_COD { get; set; }
        public string CONT_STR_BANCO { get; set; }
        public string DIGT_STR_BANCO { get; set; }
        public string AGENC_NUMERO { get; set; }
    
        public virtual INSTI_BANCO INSTI_BANCO { get; set; }
    }
}
