//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_MOEDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBRX_MOEDA()
        {
            this.EBRX_CARTEIRA = new HashSet<EBRX_CARTEIRA>();
            this.EBRX_ORDER = new HashSet<EBRX_ORDER>();
            this.EBRX_TRAN = new HashSet<EBRX_TRAN>();
        }
    
        public int MOE_STR_ID { get; set; }
        public string MOE_STR_DESC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_CARTEIRA> EBRX_CARTEIRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_ORDER> EBRX_ORDER { get; set; }
        public virtual EBRX_COTACAO EBRX_COTACAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_TRAN> EBRX_TRAN { get; set; }
    }
}
