//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfcPim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBRX_FUNC_PROFILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EBRX_FUNC_PROFILE()
        {
            this.EBRX_CLIENT_SOLICIT = new HashSet<EBRX_CLIENT_SOLICIT>();
        }
    
        public int COD_PROFILE { get; set; }
        public Nullable<int> EBRX_FUNCRH_COD { get; set; }
        public string SENH_STR_ACESS { get; set; }
        public string MATRIC_STR_ACESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EBRX_CLIENT_SOLICIT> EBRX_CLIENT_SOLICIT { get; set; }
        public virtual EBRX_FUNCRH EBRX_FUNCRH { get; set; }
    }
}
